#!/usr/bin/env python3
from ftplib import FTP_TLS
import sys

HOST = sys.argv[1]
USER = 'ftptest'
PASS = 'ftptest'

def connect():
    ftp = FTP_TLS(host=HOST)
    ftp.login(user=USER, passwd=PASS)
    return ftp

ftp = connect()

print(ftp.pwd())
